#!/bin/bash

# bcftools view --output out.test.vcf -S unrelated_ids.txt test.vcf 
# vcftools --vcf test.vcf --out out.test --remove related_ids.txt


# USAGE: ./2_vcf_filter.sh -r <PATH/related_ids.txt generated by step one> 
#                          -i <directory containing phased vcf files of all chromosomes>
#                          -o <desired output directory for all chromosome vcf files containing only unrelated individuals>
# script will filter input vcf files and output "copies" containing only unrelated individuals


while getopts r:i:o: flag
do
    case "${flag}" in
        r) related=${OPTARG};;
        i) indir=${OPTARG%/};;
        o) outdir=${OPTARG%/};;
    esac
done

# call vcftools on every chromosome vcf to filter out all related individuals
files=($( ls $indir/*.vcf ))

for i in "${files[@]}"
do
    fname="${i##*/}"
    chr="${fname%%_*}"

    # if [ "$chr" == "chr10" ] || [ "$chr" == "chr11" ] || [ "$chr" == "chr13" ] || [ "$chr" == "chr14" ] || [ "$chr" == "chr15" ] || [ "$chr" == "chr17" ];
    # then
    #     continue
    # fi

    echo "Starting $chr!"

    vcftools --vcf "$i" --out "$outdir" --remove "$related" --recode

    echo "Finished $chr!"

done