#!/bin/bash

# USAGE: ./2_vcf_filter.sh -r <path/to/related_ids.txt generated by step one> 
#                          -i <directory containing phased vcf files of all chromosomes>
#                          -o <desired output directory for all chromosome vcf files containing only unrelated individuals>
# script will filter input vcf files and output "copies" containing only unrelated individuals

# vcf files
# ~/scratch16-rmccoy22/abortvi2/vcf_phasing_array/chm13_phased_vcf_header_fixed/*.vcf


# parse arguments
usage() { echo "$0 usage:" && grep " .)\ #" $0; exit 0; }

[ $# -eq 0 ] && usage
while getopts "hr:i:o:" arg; do
    case $arg in
        r) # -r <PATH/related_ids.txt generated by step 1>
            related=${OPTARG}
            ;;
        i) # -i <directory containing phased vcf files of all chromosomes>
            indir=${OPTARG%/}
            ;;
        o) # -o <<desired output directory for all chromosome vcf files containing only unrelated individuals>
            outdir=${OPTARG%/}
            ;;            
        h | *)
            usage
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;

        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
  esac
done



# call vcftools on every chromosome vcf to filter out all related individuals
files=($( ls $indir/*.vcf ))

for i in "${files[@]}"
do
    fname="${i##*/}"
    chr="${fname%%_*}"

    prefix=$outdir/"${chr}"_unrelated_phased

    # we've already filtered this chromosome
    if [ -f "$prefix".recode.vcf ]; 
    then
        continue
    fi

    echo "Starting $chr filtering!"

    vcftools --vcf "$i" --out "$prefix" --remove "$related" --recode

    echo "Finished $chr filtering!"

done

echo "All done!"